[tox]
minversion = 3.7.0
envlist = mypy, ruff, python3.9, python3.10, python3.11, python3.12

[gh-actions]
python =
    3.9: python3.9
    3.10: python3.10

[testenv:pytest]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    pytest>=7.1.2
commands =
    pytest --basetemp={envtmpdir}


[testenv:mypy]
basepython = python3.12
deps =
    mypy>=1.8.0
commands =
    mypy --install-types
    mypy src

[testenv:ruff]
basepython = python3.12
deps =
    -e {toxinidir}[dev]
commands =
    ruff check src tests
    ruff format --check src tests
